# -*- coding: utf-8 -*-
"""week1-sms-spam-classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKhy-uYVA8ljd1PfxUiRb9y5CDjuk94Y
"""

import kagglehub

path=kagglehub.dataset_download("uciml/sms-spam-collection-dataset")

print("Path to dataset files:", path)

import numpy as np
import pandas as pd

df = pd.read_csv('/kaggle/input/sms-spam-collection-dataset/spam.csv', encoding='latin-1')

df[:4]

df=df[["v1","v2"]]

df.columns = ['label', 'message']

df

"""check for null values"""

df.isnull().sum()

"""check for duplicates"""

df.duplicated().sum()

"""clean dupliactes"""

df.drop_duplicates(keep='first',inplace=True)

"""check imbalance"""

df["label"].value_counts()

df['message'] = df["message"].str.lower()

import re

df['message'] = df['message'].apply(lambda x: re.sub(r'[^\w\s]', '', x))

import spacy

nlp=spacy.load("en_core_web_sm")

def tokenize_message(raw_text):
  doc = nlp(raw_text)
  tokens = [token.lemma_ for token in doc
            if not token.is_stop and not token.is_punct and token.is_alpha]
  return tokens

df["message_tokens"]=df["message"].apply(tokenize_message)

df.head()

"""stringing it together"""

df["processed_message"]= df["message_tokens"].apply(lambda x: " ".join(x))

df.head()

df_final = df[['label', 'processed_message']].copy()
display(df_final.head())

"""Feature Extraction / Experimentation"""

from sklearn.feature_extraction.text import CountVectorizer

cv=CountVectorizer()
X_bow=cv.fit_transform(df_final["processed_message"])

print("Matrix Shape:")
print(X_bow.shape)

# Display the first 20 unique words the vectorizer learned for its master vocabulary
print("\nFirst 20 Vocabulary Words:")
print(cv.get_feature_names_out()[:20])

print(X_bow.toarray())

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()
X=tfidf.fit_transform(df_final["processed_message"])

print("TF-IDF Matrix Shape:")
print(X.shape)

# Display a sample of the first 20 unique words the vectorizer chose for the vocabulary
print("\nFirst 20 TF-IDF Vocabulary Words:")
print(tfidf.get_feature_names_out()[:20])

from sklearn.preprocessing import LabelEncoder

# Initialize the encoder object
encoder = LabelEncoder()

# Learn the unique text labels in our dataset and convert them into numbers
# This transforms our "ham" and "spam" labels into 0s and 1s and saves them as y
y = encoder.fit_transform(df['label'])

df_final

"""Modelling"""

print(f"Features shape: {X.shape}")
print(f"Labels shape: {y.shape}")
print("Data loaded successfully! Ready to train.")

from sklearn.model_selection import train_test_split

# Split the data into 80% training and 20% testing sets
# X should be the raw processed messages (strings), not the already vectorized matrix
X_train_raw, X_test_raw, y_train, y_test = train_test_split(df_final["processed_message"], y, test_size=0.2, random_state=42)

# Verify the dimensions and type of our new datasets
print("--- Training Data Shape (raw messages) ---")
print(X_train_raw.shape)
print(f"Type of X_train_raw: {type(X_train_raw)}")
print("\n--- Testing Data Shape (raw messages) ---")
print(X_test_raw.shape)
print(f"Type of X_test_raw: {type(X_test_raw)}")

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

text_clf = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', LogisticRegression()),
])

text_clf.fit(X_train_raw, y_train)

y_pred=text_clf.predict(X_test_raw)

y_pred[:10]

"""Evaluation"""

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# Generate the matrix and define the labels in a compact format
cm = confusion_matrix(y_test, y_pred)
labels = [[f"TN: {cm[0,0]}", f"FP: {cm[0,1]}"], [f"FN: {cm[1,0]}", f"TP: {cm[1,1]}"]]

# Plot the heatmap
sns.heatmap(cm, annot=labels, fmt='', cmap='Blues', xticklabels=['Ham', 'Spam'], yticklabels=['Ham', 'Spam'], cbar=False)
plt.title('Spam Detection Confusion Matrix')
plt.show()

from sklearn.metrics import accuracy_score

# Calculate the accuracy by comparing our pre-loaded predictions to the true answers
test_accuracy = accuracy_score(y_test, y_pred)

# Print the final score formatted as a percentage
print("Test Accuracy:", test_accuracy)

from sklearn.metrics import precision_score, recall_score, f1_score

# Calculate and print the advanced classification metrics
print("Precision:", precision_score(y_test, y_pred))
print("Recall:   ", recall_score(y_test, y_pred))
print("F1 Score: ", f1_score(y_test, y_pred))